include: ^postgres_backup/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: requirements-txt-fixer          # Sorts requirements
      - id: end-of-file-fixer               # Add empty string end of each file
      - id: trailing-whitespace             # Remove extra whitespaces
      - id: check-added-large-files         # Check we do not commit vast large files
        args: ['--maxkb=1000']
      - id: double-quote-string-fixer       # Replace " by '
      - id: check-merge-conflict            # Check for unresolved merge conflicts
      - id: check-case-conflict
      - id: check-ast                       # Check .py files are valid
      - id: check-yaml                      # YML files are properly structured
      - id: check-toml
      - id: check-json
      - id: check-xml
  # - repo: 'https://github.com/psf/black'
  #   rev: 22.3.0
  #   hooks:
  #     - id: black
  #       language_version: python3
  - repo: https://github.com/pycqa/isort    # Sort input alphabetically
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-blind-except',
            'flake8-docstrings',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-docstrings',
            'flake8-implicit-str-concat',
            'pydocstyle>=5.0.0',
        ]
        exclude: tests/, parent_folder, raw_images_clean,
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: [ "bandit[toml]" ]