"""fourth rev user

Revision ID: 08036d9bd30d
Revises: e37d9955e20a
Create Date: 2022-10-24 13:43:43.961100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08036d9bd30d'
down_revision = 'e37d9955e20a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usr_user', 'user_three_id')
    op.drop_column('usr_user', 'user_two_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usr_user', sa.Column('user_two_id', mysql.CHAR(length=38), nullable=False))
    op.add_column('usr_user', sa.Column('user_three_id', mysql.CHAR(length=38), nullable=False))
    # ### end Alembic commands ###
