"""first rev

Revision ID: a104c3b16287
Revises: 
Create Date: 2022-10-24 13:34:47.075545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a104c3b16287'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usr_user',
    sa.Column('user_id', sa.CHAR(length=38), nullable=False),
    sa.Column('user_two_id', sa.CHAR(length=38), nullable=False),
    sa.Column('client_id', sa.CHAR(length=38), nullable=True),
    sa.Column('association_id', sa.CHAR(length=38), nullable=True),
    sa.Column('association_type_term', sa.VARCHAR(length=39), nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=61), nullable=True),
    sa.Column('password', sa.TEXT(), nullable=True),
    sa.Column('token', sa.TEXT(), nullable=True),
    sa.Column('status_term', sa.VARCHAR(length=39), nullable=True),
    sa.Column('profile_pic', sa.VARCHAR(length=361), nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=61), nullable=True),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.CHAR(length=39), nullable=True),
    sa.Column('updated_on', sa.DATETIME(), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=39), nullable=True),
    sa.Column('email', sa.CHAR(length=161), nullable=True),
    sa.Column('mobile_no', sa.CHAR(length=13), nullable=True),
    sa.Column('is_active', sa.String(length=1), nullable=True),
    sa.Column('is_delete', sa.String(length=1), nullable=True),
    sa.Column('update_log', sa.TIMESTAMP(), nullable=True),
    sa.Column('seq_no', sa.INTEGER(), nullable=False),
    sa.Column('user_type_term', sa.VARCHAR(length=39), nullable=True),
    sa.Column('is_default', sa.String(length=1), nullable=True),
    sa.Column('is_it_admin', sa.String(length=1), nullable=True),
    sa.Column('forgot_password_token', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('seq_no')
    )
    op.create_index(op.f('ix_usr_user_seq_no'), 'usr_user', ['seq_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usr_user_seq_no'), table_name='usr_user')
    op.drop_table('usr_user')
    # ### end Alembic commands ###
