"""datetime in usruser

Revision ID: ceac3cc7edd8
Revises: 08036d9bd30d
Create Date: 2022-10-24 19:14:04.885886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceac3cc7edd8'
down_revision = '08036d9bd30d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
